name: foto_pdf_app
description: A Flutter application for capturing photos and converting them to PDF.
version: 1.0.0+1

environment:
  sdk: ^3.2.0
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  pdf: ^3.11.0
  path_provider: ^2.1.4
  open_filex: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
